### ISSUE TITLE
Some issues...

### ISSUE THREAD

**Issue by smoothquark** [NathanaelA/minidlna#4]
Hi! Excellent piece of work - just been testing with my minidlna 1.1.4 (needed to work on the patches). Been testing with one single folder with some test files. Found some issues which I hope you can help out with...
1. Password length

My .password is "1234". However, it seems to be read as "12340"

Log:

[2015/08/31 21:21:29] scanner.c:771: warn: Scanning /media/Videos_2/Samples
[2015/08/31 21:21:29] scanner.c:731: warn: Password has a non-digit character, replacing with a 0
[2015/08/31 21:21:29] scanner.c:735: warn: Password is 12340
[2015/08/31 21:21:29] scanner.c:745: warn: Password size 5 does not match configuration password_length of 4

Once I set password_length=5 in /etc/minidlna.conf, password entry works
1. Does not work with BubbleUPNP (android)

I cannot get it to work at all (show files). Works OK with UPNP Browser on android
1. The passwords are not saved across different devices which is excellent!
2. Passwords seem to be saved for as long as the server is running. Is it possible to somehow reset the device so that it "forgets" the password? "0000" or in my case, "00000" is too draconian - I get "no movie files on device" message and cannot enter a new password unless I restart minidlna. This is so that if I watch say an 18 rated movie and then turn off the tv, I do not want the kids to turn the tv back on and be able to watch that movie.

Once again, thank you for your great work...

**Comment by smoothquark** [comment]
Hmm.. the items have been renumbered! Should be 1, 2, 3 and 4.

**Comment by NathanaelA** [comment]
@smoothquark -- On your first issue; it sounds like some other character is being sent at the end.   I should be able to eliminate it, once we know what it is.   I assume you would be willing to test patches, because I can output the ascii value of the 5th character that it is converting to a zero..

I'll have to download BubbleUPNP and test -- it worked with the one I have on my phone.

When resetting a password, why do you have to restart minidlna; it should allow you to enter a new password after that.   That sounds like you ran into a bug...    Do you have all your folders password protected or just some; and the kids folder left unprotected?

**Comment by smoothquark** [comment]
Thanks for the quick response. Got BubbleUPNP to work - don't know why the passwords did not work previously. Perhaps I may have just typed it wrong. Works now as expected. Shall try to debug the spurious character...

**Comment by smoothquark** [comment]
Spoke too soon about BubbleUPNP. Tried again.... Restarted minidlna to reset. Entered password on BubbleUPNP - no videos shown. Exited and restarted BubbleUPNP - able to browse video titles. Somehow refresh is not happening?

Anyway, been debugging the password...

[2015/09/01 10:14:46] scanner.c:772: warn: Scanning /media/Videos_2/Samples
[2015/09/01 10:14:46] scanner.c:729: warn: Password length = 5
[2015/09/01 10:14:46] scanner.c:731: warn: Password character 0 = 1
[2015/09/01 10:14:46] scanner.c:731: warn: Password character 1 = 2
[2015/09/01 10:14:46] scanner.c:731: warn: Password character 2 = 3
[2015/09/01 10:14:46] scanner.c:731: warn: Password character 3 = 4
[2015/09/01 10:14:46] scanner.c:731: warn: Password character 4 = 

[2015/09/01 10:14:46] scanner.c:733: warn: Password has a non-digit character, replacing with a 0
[2015/09/01 10:14:48] scanner.c:866: warn: Scanning /media/Videos_2/Samples finished (9 files)!

Password is "1234". Somehow another character is creeping in.

**Comment by smoothquark** [comment]
Managed to figure out the password spurious character issue. I think it has got to do with fgets adding in a line feed (\n) - confirmed as ASCII 10 when I printed out each char.
Added a line in scanner.c (line no.728) and seems to work
if (!p) {
    password[0] = 0;
}
password[strcspn(password, "\r\n")] = 0; // remove LF, CR, CRLF, LFCR, ...

Shall see if I can figure out the other 2 issues....

**Comment by bl4ckb1rd77** [comment]
regarding the issue descriped by @smoothquark

when i enter 0000 so that minidlna forget all entered passwords from client.
minidlna diappeard from network.
log display no issues

`[2016/06/13 18:41:53] upnphttp.c:653: debug: SOAPAction: urn:schemas-upnp-org:service:ContentDirectory:1#Browse
[2016/06/13 18:41:53] upnpsoap.c:2146: debug: SoapMethod: Browse
[2016/06/13 18:41:53] upnpsoap.c:1399: debug: Browsing ContentDirectory:
- ObjectID: 32$0$0$0$0
- Count: 1000
- StartingIndex: 0
- BrowseFlag: BrowseDirectChildren
- Filter: *
- SortCriteria: (null)
  [2016/06/13 18:41:53] upnpsoap.c:1433: info: Is Password 32$0$0$0$0[2016/06/13 18:41:53] upnphttp.c:1216: debug: HTTP RESPONSE: HTTP/1.1 200 OK
  Content-Type: text/xml; charset="utf-8"
  Connection: close
  Content-Length: 633
  Server: 4.1.19-v7+ DLNADOC/1.50 UPnP/1.0 MiniDLNA/1.1.4
  Date: Mon, 13 Jun 2016 16:41:53 GMT
  EXT:

<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:BrowseResponse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><Result>&lt;DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/"&gt;
&lt;/DIDL-Lite&gt;</Result>
<NumberReturned>0</NumberReturned>
<TotalMatches>0</TotalMatches>
<UpdateID>555</UpdateID>/u:BrowseResponse/s:Body/s:Envelope

[2016/06/13 18:41:53] minidlna.c:1267: debug: HTTP connection from 192.168.178.88:44273
[2016/06/13 18:41:53] clients.c:274: debug: Client found in cache. [Generic UPnP 1.0/entry 2]
[2016/06/13 18:41:53] upnphttp.c:880: debug: HTTP REQUEST: POST /ctl/ContentDir HTTP/1.1
HOST: 192.168.178.128:8200
CONTENT-LENGTH: 449
CONTENT-TYPE: text/xml; charset="utf-8"
SOAPACTION: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
USER-AGENT: Linux/3.10.84-perf-gc339a66, UPnP/1.0, Portable SDK for UPnP devices/1.6.19

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body><u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
<ObjectID>32$0$0$0$1</ObjectID>
<BrowseFlag>BrowseDirectChildren</BrowseFlag>
<Filter>*</Filter>
<StartingIndex>0</StartingIndex>
<RequestedCount>1000</RequestedCount>
<SortCriteria></SortCriteria>
/u:Browse
/s:Body
/s:Envelope

[2016/06/13 18:41:53] upnphttp.c:653: debug: SOAPAction: urn:schemas-upnp-org:service:ContentDirectory:1#Browse
[2016/06/13 18:41:53] upnpsoap.c:2146: debug: SoapMethod: Browse
[2016/06/13 18:41:53] upnpsoap.c:1399: debug: Browsing ContentDirectory:
- ObjectID: 32$0$0$0$1
- Count: 1000
- StartingIndex: 0
- BrowseFlag: BrowseDirectChildren
- Filter: *
- SortCriteria: (null)
  [2016/06/13 18:41:53] upnpsoap.c:1433: info: Is Password 32$0$0$0$1
  `

service stopped working.

`# service minidlna status
minidlna is not running ... failed!
`
so i guess that forgot password lead to an exception that stopped the service.

System:
PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
on an Raspberry PI 3 with openmediavault.

**Comment by NathanaelA** [comment]
Interesting.   I should probably update this code base to the latest minidlna code base and see if that fixes some of these issues.

**Comment by bl4ckb1rd77** [comment]
that would be great.
i will then check and report back.

cheers,

2016-06-13 19:47 GMT+02:00 Nathanael Anderson notifications@github.com:

**Comment by NathanaelA** [comment]
@m4st3r-bl4ckb1rd thanks for updating the source to 1.1.6; I've fixed a small issue that was introduced in the update; and also applied a fix for the first password issue that @smoothquark  was seeing.

**Comment by NathanaelA** [comment]
Some additional password fixes went into the v1.2.1 release I just did a couple weeks ago.
